const shows2025={
  'United Kingdom & Ireland':[['24 MAY','Liverpool, England','Sefton Park · BBC Radio 1 Big Weekend'],['06 JUN','London, England','London Stadium'],['12 JUN','Newcastle, England','St James’ Park'],['14 JUN','Newcastle, England','St James’ Park'],['15 JUN','Newcastle, England','St James’ Park'],['03 JUL','Silverstone, England','Silverstone Circuit'],['16 AUG','Manchester, England','Wythenshawe Park'],['22 AUG','Edinburgh, Scotland','Royal Highland Showgrounds'],['28 AUG','Belfast, Northern Ireland','Boucher Road Playing Fields · VITAL'],['30 AUG','Stradbally, Ireland','Stradbally Hall · Electric Picnic']],
  'Continental Europe':[['04 MAR','Paris, France','L’Olympia'],['05 MAR','Tilburg, Netherlands','013'],['08 MAR','Zurich, Switzerland','Halle 622'],['10 MAR','Cologne, Germany','Palladium'],['12 MAR','Munich, Germany','Zenith'],['13 MAR','Bergamo, Italy','ChorusLife Arena'],['16 MAR','Berlin, Germany','Uber Eats Music Hall'],['18 MAR','Amsterdam, Netherlands','AFAS Live'],['19 MAR','Brussels, Belgium','Forest National'],['21 JUN','Scheeßel, Germany','Eichenring · Hurricane Festival'],['22 JUN','Neuhausen ob Eck, Germany','Take Off Park · Southside Festival'],['08 AUG','Copenhagen, Denmark','Valbyparken · Syd for Solen']],
  'United States':[['07 APR','Seattle, Washington','Paramount Theatre'],['09 APR','Portland, Oregon','Roseland Theater'],['11 APR','Oakland, California','Fox Theater'],['21 APR','Tempe, Arizona','Marquee Theater'],['23 APR','Salt Lake City, Utah','The Union Event Center'],['24 APR','Denver, Colorado','The Fillmore'],['17 SEP','Boston, Massachusetts','Roadrunner'],['19 SEP','New York, New York','Terminal 5'],['21 SEP','Philadelphia, Pennsylvania','The Fillmore'],['23 SEP','Washington, D.C.','The Anthem'],['25 SEP','Chicago, Illinois','Aragon Ballroom'],['27 SEP','St. Louis, Missouri','Forest Park · Evolution Festival'],['28 SEP','Franklin, Tennessee','The Park at Harlinsdale Farm · Pilgrimage Festival']],
  Canada:[['05 APR','Vancouver, British Columbia','Doug Mitchell Thunderbird Sports Centre'],['01 OCT','Laval, Quebec','Place Bell'],['03 OCT','Toronto, Ontario','Coca-Cola Coliseum']],
  Australia:[['14 NOV','Melbourne, Victoria','Sidney Myer Music Bowl'],['15 NOV','Melbourne, Victoria','Sidney Myer Music Bowl'],['19 NOV','Brisbane, Queensland','Riverstage'],['21 NOV','Sydney, New South Wales','The Showring · Entertainment Quarter'],['25 NOV','Adelaide, South Australia','Entertainment Centre Arena'],['28 NOV','Perth, Western Australia','Kings Park']],
  'Festivals & special appearances':[['01 MAR','London, England','The O2 Arena · BRIT Awards 2025'],['12 APR','Indio, California','Empire Polo Club · Coachella Weekend 1'],['16 APR','Los Angeles, California','Jimmy Kimmel Live'],['19 APR','Indio, California','Empire Polo Club · Coachella Weekend 2'],['25 MAY','North Shields, England','The Murphy · Special appearance'],['16 OCT','Newcastle, England','Utilita Arena · Mercury Prize']]
};
const londonStadiumSongs=['Going Home: Theme of the Local Hero','Getting Started','Will We Talk?','Arm’s Length','The Borders','Dead Boys','Howdon Aldi Death Queue','Crumbling Empire','Tyrants','Rein Me In (with Olivia Dean)','People Watching','London Calling','Get You Down','Spit of You','Seventeen Going Under','Remember My Name','The Dying Light','Hypersonic Missiles'];
const recentSetlists={
  '01 MAR|The O2 Arena · BRIT Awards 2025':{url:'https://www.setlist.fm/setlist/sam-fender/2025/the-o2-arena-london-england-235b98f7.html',songs:['People Watching']},
  '04 MAR|L’Olympia':{url:'https://www.setlist.fm/setlist/sam-fender/2025/lolympia-bruno-coquatrix-paris-france-5b5f9bf4.html',songs:['Getting Started','Arm’s Length','People Watching','Crumbling Empire (live debut)','Will We Talk?','Tyrants (live debut)','Howdon Aldi Death Queue','TV Dinner (live debut)','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Chin Up (live debut)','Encore — Hypersonic Missiles'],note:'Nostalgia’s Lie was printed but not played.'},
  '05 MAR|013':{url:'https://www.setlist.fm/setlist/sam-fender/2025/poppodium-013-tilburg-netherlands-7b5072e4.html',songs:['Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Nostalgia’s Lie','Encore — Hypersonic Missiles']},
  '08 MAR|Halle 622':{url:'https://www.setlist.fm/setlist/sam-fender/2025/halle-622-zurich-switzerland-4b50572e.html',songs:['Something Heavy (live debut)','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Hypersonic Missiles']},
  '10 MAR|Palladium':{url:'https://www.setlist.fm/setlist/sam-fender/2025/palladium-cologne-germany-1351bdc5.html',songs:['Nostalgia’s Lie (first time as show opener)','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Something Heavy (with I’m Always on Stage guitar intro)','Encore — Hypersonic Missiles']},
  '12 MAR|Zenith':{url:'https://www.setlist.fm/setlist/sam-fender/2025/zenith-munich-germany-1b51bdc4.html',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '13 MAR|ChorusLife Arena':{url:'https://www.setlist.fm/setlist/sam-fender/2025/choruslife-arena-bergamo-italy-1b51bdbc.html',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Something Heavy (with I’m Always on Stage guitar intro)','Encore — Hypersonic Missiles']},
  '16 MAR|Uber Eats Music Hall':{url:'https://www.setlist.fm/setlist/sam-fender/2025/uber-eats-music-hall-berlin-germany-b51bdb2.html',songs:['Going Home: Theme of the Local Hero (Mark Knopfler cover)','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You (restarted after Sam forgot the lyrics)','The Borders (with fan Ben on guitar)','Little Bit Closer','Seventeen Going Under','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '18 MAR|AFAS Live':{url:'https://www.setlist.fm/setlist/sam-fender/2025/afas-live-amsterdam-netherlands-5b507338.html',songs:['Getting Started','Arm’s Length','People Watching','Happy Birthday to You (for Stevie Harper)','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders (with fan Scott on guitar)','Little Bit Closer','Seventeen Going Under','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '19 MAR|Forest National':{url:'https://www.setlist.fm/setlist/sam-fender/2025/vorst-nationaal-forest-national-vorst-forest-belgium-3350685d.html',songs:['Going Home: Theme of the Local Hero (Mark Knopfler cover)','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders','Little Bit Closer','Nostalgia’s Lie','Seventeen Going Under','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '05 APR|Doug Mitchell Thunderbird Sports Centre':{url:'https://www.setlist.fm/setlist/sam-fender/2025/doug-mitchell-thunderbird-sports-centre-vancouver-bc-canada-235ee097.html',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','TV Dinner','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '24 MAY|Sefton Park · BBC Radio 1 Big Weekend':{url:'https://www.setlist.fm/search?artist=2bcf0832&year=2025&cityName=Liverpool',songs:['Getting Started','The Borders','Will We Talk?','People Watching','Arm’s Length','Howdon Aldi Death Queue','Tyrants','Spit of You','Little Bit Closer','Seventeen Going Under','Hypersonic Missiles']},
  '06 JUN|London Stadium':{url:'https://www.setlist.fm/setlist/sam-fender/2025/london-stadium-london-england-235e7857.html',songs:londonStadiumSongs},
  '12 JUN|St James’ Park':{url:'https://www.setlist.fm/setlist/sam-fender/2025/st-james-park-newcastle-upon-tyne-england-335e7851.html',songs:['Going Home: Theme of the Local Hero','Getting Started','Will We Talk?','Arm’s Length','The Borders','Dead Boys','Howdon Aldi Death Queue','Crumbling Empire','Tyrants','Something Heavy','People Watching','The Boys Are Back in Town','Get You Down','Spit of You','Seventeen Going Under','Remember My Name','The Dying Light','Hypersonic Missiles'],note:'Walk-on tape: UEFA Champions League Anthem.'},
  '14 JUN|St James’ Park':{url:'https://www.setlist.fm/setlist/sam-fender/2025/st-james-park-newcastle-upon-tyne-england-3b5e7850.html',songs:['Going Home: Theme of the Local Hero','Getting Started','Will We Talk?','Arm’s Length','The Borders','Dead Boys','Howdon Aldi Death Queue','Crumbling Empire','Tyrants','Rein Me In (with Olivia Dean)','People Watching','The Boys Are Back in Town','Get You Down','Spit of You','Seventeen Going Under','Remember My Name','The Dying Light','Hypersonic Missiles'],note:'Walk-on tape: UEFA Champions League Anthem.'},
  '15 JUN|St James’ Park':{url:'https://www.setlist.fm/setlist/sam-fender/2025/st-james-park-newcastle-upon-tyne-england-4b5fe792.html',songs:['Going Home: Theme of the Local Hero','Getting Started','Will We Talk?','Arm’s Length','The Borders','Howdon Aldi Death Queue','Crumbling Empire','Tyrants','Rein Me In (with Olivia Dean)','People Watching','The Boys Are Back in Town','Get You Down','Spit of You','Seventeen Going Under','Remember My Name','The Dying Light','Hypersonic Missiles'],note:'Walk-on tape: UEFA Champions League Anthem.'},
  '21 JUN|Eichenring · Hurricane Festival':{url:'https://www.setlist.fm/setlist/sam-fender/2025/eichenring-river-stage-scheessel-germany-b5f9936.html',songs:['Getting Started','Will We Talk?','Arm’s Length','The Borders (with fan Lenny on stage)','Howdon Aldi Death Queue','Tyrants','Crumbling Empire','People Watching','I’m Always on Stage','Spit of You','Seventeen Going Under','Hypersonic Missiles']},
  '22 JUN|Take Off Park · Southside Festival':{url:'https://www.setlist.fm/setlist/sam-fender/2025/take-off-gewerbepark-blue-stage-neuhausen-ob-eck-germany-6b5f9e86.html',songs:['Getting Started','Will We Talk?','The Borders','Arm’s Length','Howdon Aldi Death Queue','Tyrants','Crumbling Empire','People Watching','Spit of You','Seventeen Going Under','Hypersonic Missiles']},
  '03 JUL|Silverstone Circuit':{url:'https://www.setlist.fm/setlist/sam-fender/2025/silverstone-circuit-silverstone-england-2b5b846a.html',songs:['Getting Started','Arm’s Length','The Borders','Howdon Aldi Death Queue','Tyrants','Crumbling Empire','People Watching','Spit of You','Seventeen Going Under','Hypersonic Missiles']},
  '08 AUG|Valbyparken · Syd for Solen':{url:'https://www.setlist.fm/setlist/sam-fender/2025/valbyparken-copenhagen-denmark-435dcb5b.html',songs:['Getting Started','Will We Talk?','Arm’s Length','The Borders','Howdon Aldi Death Queue','Tyrants','Crumbling Empire','People Watching','Spit of You','Seventeen Going Under','Hypersonic Missiles (with Greta Thunberg; preceded by pro-Palestine chant)']},
  '16 AUG|Wythenshawe Park':{url:'https://www.setlist.fm/setlist/sam-fender/2025/wythenshawe-park-manchester-england-135a6119.html',songs:['Angel in Lothian','Spice','Will We Talk?','Getting Started','Arm’s Length','The Borders','Crumbling Empire','Dead Boys','People Watching','Tyrants','Howdon Aldi Death Queue','Alright','Spit of You','Seventeen Going Under','Hypersonic Missiles']},
  '22 AUG|Royal Highland Showgrounds':{url:'https://www.setlist.fm/setlist/sam-fender/2025/royal-highland-centre-showground-ingliston-scotland-535ba7d5.html',songs:['Angel in Lothian','Spice','Will We Talk?','Getting Started','Arm’s Length','The Borders (with fan Cara)','Rein Me In (with Olivia Dean)','Crumbling Empire','People Watching','Alright','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Hypersonic Missiles'],note:'Sam’s first Edinburgh show since 2018. Something Heavy was printed but not played.'},
  '28 AUG|Boucher Road Playing Fields · VITAL':{url:'https://www.setlist.fm/setlist/sam-fender/2025/boucher-road-playing-fields-belfast-northern-ireland-335ba0a9.html',songs:['Angel in Lothian','Spice','Will We Talk?','Getting Started','Arm’s Length','The Borders (with fan Holly on acoustic guitar)','Crumbling Empire','People Watching','Alright','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — I’m Always on Stage (first UK performance)','Encore — Hypersonic Missiles'],note:'Something Heavy was printed but not played.'},
  '30 AUG|Stradbally Hall · Electric Picnic':{url:'https://www.setlist.fm/setlist/sam-fender/2025/stradbally-hall-stradbally-ireland-33585ccd.html',songs:['Angel in Lothian','Spice','Will We Talk?','Getting Started','Arm’s Length','The Borders','Crumbling Empire','People Watching','Alright','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','The Dying Light','Something Heavy','Hypersonic Missiles']},
  '19 APR|Empire Polo Club · Coachella Weekend 2':{url:'https://www.setlist.fm/setlist/sam-fender/2025/empire-polo-club-indio-ca-35e090b.html',songs:['The Borders','Arm’s Length','Spit of You','Howdon Aldi Death Queue','People Watching (with Adam Granduciel)','Tyrants (with Adam Granduciel)','Seventeen Going Under (with Adam Granduciel)','Hypersonic Missiles (with Adam Granduciel)']},
  '07 APR|Paramount Theatre':{url:'https://www.setlist.fm/setlist/sam-fender/2025/paramount-theatre-seattle-wa-335ee095.html',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','Nostalgia’s Lie','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — I’m Always on Stage (full debut)','Encore — Hypersonic Missiles']},
  '09 APR|Roseland Theater':{url:'https://www.setlist.fm/setlist/sam-fender/2025/roseland-theater-portland-or-3b5ee094.html',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','Nostalgia’s Lie','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Angel in Lothian (audience request)','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '11 APR|Fox Theater':{url:'https://www.setlist.fm/setlist/sam-fender/2025/fox-theater-oakland-ca-335ee089.html',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue (extended)','Nostalgia’s Lie','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '12 APR|Empire Polo Club · Coachella Weekend 1':{url:'https://www.setlist.fm/setlist/sam-fender/2025/empire-polo-club-indio-ca-1b5e0914.html',songs:['Getting Started','Arm’s Length','The Borders','Howdon Aldi Death Queue','People Watching','Spit of You','Seventeen Going Under','Hypersonic Missiles']},
  '21 APR|Marquee Theater':{url:'https://www.setlist.fm/search?artist=2bcf0832&year=2025&cityName=Tempe',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','Nostalgia’s Lie','Spit of You','The Borders','All Is on My Side (audience request)','Seventeen Going Under','Encore — I’m Always on Stage','Encore — Hypersonic Missiles']},
  '23 APR|The Union Event Center':{url:'https://www.setlist.fm/setlist/sam-fender/2025/the-union-event-center-salt-lake-city-ut-2b5ee08e.html',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','Nostalgia’s Lie','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — I’m Always on Stage','Encore — Hypersonic Missiles']},
  '24 APR|The Fillmore':{url:'https://www.setlist.fm/search?artist=2bcf0832&year=2025&cityName=Denver',songs:['Dead Boys','Getting Started','Arm’s Length','People Watching','Crumbling Empire','Will We Talk?','Tyrants','Howdon Aldi Death Queue','Nostalgia’s Lie','Spit of You','The Borders','Little Bit Closer','Seventeen Going Under','Encore — I’m Always on Stage','Encore — Willin’ (Little Feat cover, with Young Jesus)','Encore — Happy Birthday to You','Encore — Hypersonic Missiles']},
  '17 SEP|Roadrunner':{url:'https://www.setlist.fm/setlist/sam-fender/2025/roadrunner-boston-ma-5b477b24.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Tyrants','Spit of You','Seventeen Going Under','The Dying Light','Happy Birthday to You','Hypersonic Missiles']},
  '19 SEP|Terminal 5':{url:'https://www.setlist.fm/setlist/sam-fender/2025/terminal-5-new-york-ny-4b477b1a.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders (with a fan on acoustic guitar)','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Tyrants','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '21 SEP|The Fillmore':{url:'https://www.setlist.fm/setlist/sam-fender/2025/the-fillmore-philadelphia-philadelphia-pa-4b477b1e.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Tyrants','Happy Birthday to You','Spit of You','Seventeen Going Under','The Dying Light','Something Heavy','Hypersonic Missiles']},
  '23 SEP|The Anthem':{url:'https://www.setlist.fm/setlist/sam-fender/2025/the-anthem-washington-dc-43477b13.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders (with a fan on acoustic guitar)','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Tyrants','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Spice (audience request)','Encore — Hypersonic Missiles']},
  '25 SEP|Aragon Ballroom':{url:'https://www.setlist.fm/search?artist=2bcf0832&year=2025&cityName=Chicago',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Love Is a Long Road (Tom Petty cover)','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '27 SEP|Forest Park · Evolution Festival':{url:'https://www.setlist.fm/setlist/sam-fender/2025/forest-park-st-louis-mo-53477b09.html',songs:['Angel in Lothian','Getting Started','Arm’s Length','The Borders','Talk to You','People Watching','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Hypersonic Missiles'],note:'First show in Missouri.'},
  '28 SEP|The Park at Harlinsdale Farm · Pilgrimage Festival':{url:'https://www.setlist.fm/setlist/sam-fender/2025/the-park-at-harlinsdale-farm-franklin-tn-4346b3f7.html',songs:['Angel in Lothian','Getting Started','Arm’s Length','The Borders','Talk to You','People Watching','Spit of You','Something Heavy','Seventeen Going Under','Hypersonic Missiles']},
  '01 OCT|Place Bell':{url:'https://www.setlist.fm/setlist/sam-fender/2025/place-bell-laval-qc-canada-43477b07.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders (with fan Roxanne on acoustic guitar)','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '03 OCT|Coca-Cola Coliseum':{url:'https://www.setlist.fm/setlist/sam-fender/2025/coca-cola-coliseum-toronto-on-canada-5b477b54.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders (with Jack Burn)','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Ohio (Crosby, Stills, Nash & Young cover, with Young Jesus; live debut)','Encore — Something Heavy','Encore — Hypersonic Missiles']},
  '14 NOV|Sidney Myer Music Bowl':{url:'https://www.setlist.fm/setlist/sam-fender/2025/sidney-myer-music-bowl-melbourne-australia-1347e105.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','The Borders','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — I’m Always on Stage (Sam solo)','Encore — The Dying Light','Encore — Hypersonic Missiles']},
  '15 NOV|Sidney Myer Music Bowl':{url:'https://www.setlist.fm/setlist/sam-fender/2025/sidney-myer-music-bowl-melbourne-australia-2b473826.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Hypersonic Missiles']},
  '19 NOV|Riverstage':{url:'https://www.setlist.fm/setlist/sam-fender/2025/riverstage-brisbane-australia-4b47fbe2.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders (with fan Izzy on guitar)','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Hypersonic Missiles']},
  '21 NOV|The Showring · Entertainment Quarter':{url:'https://www.setlist.fm/setlist/sam-fender/2025/the-entertainment-quarter-sydney-australia-b47e1fa.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Hypersonic Missiles']},
  '25 NOV|Entertainment Centre Arena':{url:'https://www.setlist.fm/setlist/sam-fender/2025/adelaide-entertainment-centre-adelaide-australia-1347e1f9.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders (with fan Andrew on guitar)','Crumbling Empire','People Watching','Talk to You','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Something Heavy (with Holly Humberstone)','Encore — Hypersonic Missiles']},
  '28 NOV|Kings Park':{url:'https://www.setlist.fm/setlist/sam-fender/2025/kings-park-and-botanic-garden-perth-australia-b47f9ca.html',songs:['Angel in Lothian','Will We Talk?','Getting Started','Arm’s Length','Wild Long Lie','The Borders (with fan Will on guitar)','Crumbling Empire','People Watching','Talk to You','Get You Down','Howdon Aldi Death Queue','Spit of You','Seventeen Going Under','Encore — The Dying Light','Encore — Something Heavy (with Holly Humberstone)','Encore — Hypersonic Missiles'],note:'Final show of the People Watching era.'},
  '16 APR|Jimmy Kimmel Live':{url:'https://www.setlist.fm/setlist/sam-fender/2025/jimmy-kimmel-live-los-angeles-ca-33594cdd.html',songs:['People Watching']},
  '25 MAY|The Murphy · Special appearance':{url:'https://www.setlist.fm/setlist/sam-fender/2025/the-murphy-north-shields-england-4b477796.html',songs:['Born to Run (Bruce Springsteen cover)']},
  '16 OCT|Utilita Arena · Mercury Prize':{url:'https://www.setlist.fm/setlist/sam-fender/2025/utilita-arena-newcastle-upon-tyne-england-7b410260.html',songs:['People Watching','People Watching (Mercury Prize reprise)']}
};
const coverArtist2025={'Going Home: Theme of the Local Hero':'Mark Knopfler','The Boys Are Back in Town':'Thin Lizzy','London Calling':'The Clash','Born to Run':'Bruce Springsteen','Love Is a Long Road':'Tom Petty','Willin’':'Little Feat','Ohio':'Crosby, Stills, Nash & Young'};
Object.values(recentSetlists).forEach(record=>{
  record.songs=record.songs.map(song=>{
    if(/\bcover\b/i.test(song))return song;
    const title=Object.keys(coverArtist2025).find(name=>song===name||song.startsWith(`${name} (`)||song.startsWith(`${name} —`));
    return title?`${song} — ${coverArtist2025[title]} cover`:song;
  });
});
window.samShows2025=Object.entries(shows2025).flatMap(([region,shows])=>shows.map(([date,cityLabel,venue])=>{
  const cityParts=cityLabel.split(',').map(part=>part.trim());
  const countryAliases={'England':'England','Scotland':'Scotland','Northern Ireland':'Northern Ireland','Ireland':'Ireland','France':'France','Netherlands':'Netherlands','Switzerland':'Switzerland','Germany':'Germany','Italy':'Italy','Belgium':'Belgium','Denmark':'Denmark'};
  let country=cityParts[cityParts.length-1];
  if(region==='United States'||/California|Washington|Oregon|Arizona|Utah|Colorado|Massachusetts|New York|Pennsylvania|Illinois|Missouri|Tennessee|D\.C\./.test(country))country='United States';
  if(region==='Canada')country='Canada';
  if(region==='Australia')country='Australia';
  country=countryAliases[country]||country;
  const record=recentSetlists[`${date}|${venue}`];
  return {year:2025,date:`${date}${date==='2025'?'':' 2025'}`,country,city:cityParts.slice(0,-1).join(', ')||cityParts[0],venue,url:record?.url||`https://www.setlist.fm/search?artist=2bcf0832&year=2025&cityName=${encodeURIComponent(cityParts[0])}`,songs:record?.songs||[],eventType:/BRIT Awards/i.test(venue)?'Awards show':/Festival|Coachella|VITAL|Electric Picnic|Silverstone|Showgrounds|Wythenshawe|Syd for Solen|Pilgrimage|Hurricane|Southside/i.test(venue)?'Festival':/Kimmel|Mercury|Murphy/i.test(venue)?'Broadcast / special appearance':'Tour',eventName:/Festival|Coachella|VITAL|Electric Picnic|Silverstone|Showgrounds|Wythenshawe|Syd for Solen|Pilgrimage|Hurricane|Southside|BRIT Awards/i.test(venue)?venue:/Kimmel|Mercury|Murphy/i.test(venue)?venue:'People Watching'};
}));
const venueCapacities={'London Stadium':'82,500','St James’ Park':'52,000+','Paramount Theatre':'2,807','Fox Theater':'2,800','Roadrunner':'3,500','Terminal 5':'3,000','The Anthem':'6,000','Aragon Ballroom':'5,000','Place Bell':'10,062','Coca-Cola Coliseum':'8,140','Sidney Myer Music Bowl':'12,000+','Riverstage':'9,500','Doug Mitchell Thunderbird Sports Centre':'7,500'};
const cityGroup=(country,shows)=>`<details class="country-group"><summary><b>${country}</b><span>${shows.length} exact shows ＋</span></summary>${shows.map(([date,city,venue])=>{const record=recentSetlists[`${date}|${venue}`],capacity=venueCapacities[venue]||(/Festival|Park|Circuit|Showgrounds|Fields|Stradbally|Coachella/i.test(venue)?'Festival / outdoor layout':'Not publicly verified');return `<details class="city-group"><summary><b>${city}</b><span>${date} 2025</span></summary><div class="venue-shows"><details class="venue-show show-entry ${record?'has-setlist':'setlist-unknown'}"><summary><span><small>${date}${date==='2025'?'':' 2025'}</small><strong>${venue}</strong><small class="venue-capacity">CAPACITY · ${capacity}</small></span><b>${record?`${record.songs.length} SETLIST ENTRIES`:'SETLIST UNKNOWN'} ＋</b></summary><div class="show-setlist-body">${record?`<ol>${record.songs.map(song=>`<li>${song}</li>`).join('')}</ol>${record.note?`<p class="archive-gap">${record.note}</p>`:''}<a href="${record.url}" target="_blank" rel="noreferrer">Setlist.fm show record ↗</a>`:`<p class="unknown-message"><b>Setlist unknown.</b> The show is documented, but a reliable song list has not been published.</p><a href="https://www.setlist.fm/search?artist=2bcf0832&amp;year=2025&amp;cityName=${encodeURIComponent(city.split(',')[0])}" target="_blank" rel="noreferrer">Check Setlist.fm ↗</a>`}</div></details></div></details>`}).join('')}</details>`;
const shows2025ByCountry=window.samShows2025.reduce((countries,show)=>{(countries[show.country]??=[]).push([show.date.replace(/ 2025$/,''),`${show.city}, ${show.country}`,show.venue]);return countries},{});
const monthNumber={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11};
const showDateValue=([date])=>{const [day,month]=date.split(' ');return monthNumber[month]*31+Number(day)};
Object.values(shows2025ByCountry).forEach(shows=>shows.sort((a,b)=>showDateValue(a)-showDateValue(b)));
setTimeout(()=>{
  const browser=document.querySelector('[data-year-view="2025"] .show-browser');
  if(browser)browser.innerHTML=`<h4>Every 2025 show · country → city → exact venue</h4><p class="data-note">Each country appears once and is ranked by its number of shows. Every city and performance is separate, including multi-night runs and awards appearances.</p><section class="concert-film london-stadium-film"><div><small>ENGLAND · LONDON · 06 JUN 2025</small><h5>Live at London Stadium</h5><p>The official concert film belongs to the London Stadium show below—not to the country listed beside it.</p><a href="https://www.setlist.fm/setlist/sam-fender/2025/london-stadium-london-england-235e7857.html" target="_blank" rel="noreferrer">OPEN THE LONDON STADIUM SETLIST ↗</a></div><iframe src="https://www.youtube-nocookie.com/embed/n8VHVN3w4Fs" title="Sam Fender live at London Stadium in 2025" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></section>${Object.entries(shows2025ByCountry).sort(([,a],[,b])=>b.length-a.length).map(([country,shows])=>cityGroup(country,shows)).join('')}`;
  const archive=document.querySelector('.live-archive');
  if(archive&&!archive.querySelector('.guest-appearances'))archive.insertAdjacentHTML('afterbegin',`<section class="guest-appearances"><div class="guest-head"><span>2026 · GUEST APPEARANCES</span><h4>Rein Me In,<br>around the world.</h4></div><div class="guest-grid"><article><time>01 MAY 2026</time><b>Olivia Dean</b><p>The O2 · London<br>“Rein Me In”</p></article><article><time>02 MAY 2026</time><b>Olivia Dean</b><p>The O2 · London<br>“Rein Me In”</p></article><article><time>11 JUL 2026</time><b>Lewis Capaldi</b><p>BST Hyde Park · London<br>“Rein Me In”</p><iframe src="https://www.youtube-nocookie.com/embed/GpB18MIw3y0" title="Sam Fender and Lewis Capaldi perform Rein Me In at Hyde Park" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></article><article><time>02 AUG 2026</time><b>Olivia Dean</b><p>Lollapalooza · Chicago<br>“Rein Me In”</p><a href="#photos">Watch the Lollapalooza video ↑</a></article></div></section>`);
},220);

setTimeout(()=>{
  const mayOne=[...document.querySelectorAll('.guest-grid article')].find(card=>card.querySelector('time')?.textContent.includes('01 MAY 2026'));
  if(mayOne&&!mayOne.querySelector('iframe'))mayOne.insertAdjacentHTML('beforeend','<iframe src="https://www.youtube-nocookie.com/embed/rgUMsAg8Gck" title="Sam Fender and Olivia Dean perform Rein Me In at The O2 London night one" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><a href="https://youtube.com/shorts/rgUMsAg8Gck" target="_blank" rel="noreferrer">Watch O2 night one on YouTube ↗</a>');
  const mayTwo=[...document.querySelectorAll('.guest-grid article')].find(card=>card.querySelector('time')?.textContent.includes('02 MAY 2026'));
  if(mayTwo&&!mayTwo.querySelector('iframe'))mayTwo.insertAdjacentHTML('beforeend','<iframe src="https://www.youtube-nocookie.com/embed/2pKkCSNEuwc" title="Sam Fender and Olivia Dean perform Rein Me In at The O2 London night two" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>');
},360);
